defaults:
  - _self_
  - env: forward_locomotion_roboclip
  - override hydra/launcher: local
  - override hydra/output: local

hydra:
  job:
    chdir: True

iteration: 1
sample: 1 # number of Eureka samples to generate per iteration


debug: False # Set to true to repipe stdout and stderr to console 

# Weights and Biases
use_wandb: False # whether to use wandb for logging
wandb_username: "" # wandb username if logging with wandb
wandb_project: "" # wandb project if logging with wandb